[package]
name = "lucifer-tile-editor"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { version = "^1.2", features = ["fltk-bundled"] }
fltk-flex = "0.2"
fltk-theme = "0.4"
